// <auto-generated />
namespace am_pm_solutions.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_campo_Pais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_campo_Pais));
        
        string IMigrationMetadata.Id
        {
            get { return "202009161325484_Add_campo_Pais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
